#!/bin/bash

BASE="/Users/music_lab/Documents/Security Engineer Portfolio/VAST Space/aegis"
POLICY="$BASE/generated/policies/haven_update_policy.rego"
ARTIFACT="$BASE/generated/policies/update_artifact.json"
HARDENED="$BASE/generated/policies/update_artifact_hardened.json"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     AEGIS — OPA/Conftest Policy Gate Demo                    ║"
echo "║     Haven-1 Flight Software Update Pipeline                  ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Countermeasure: CM0034 — SBOM + Build Provenance"
echo "  NIST Controls:  SA-12, SA-12(1), SR-4"
echo "  Blocks:         IA-0009.02 Supply Chain Compromise"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  BEFORE — No policy gate"
echo "  Artifact: haven1-fsw-update.bin (compromised CI/CD output)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Running without policy..."
echo ""
echo "  [CICD] Build artifact accepted"
echo "  [CICD] Signing with build key..."
echo "  [CICD] Artifact signed — uploading to Haven-1 OBC"
echo "  [OBC]  Update received — validating signature..."
echo "  [OBC]  Signature valid — installing update"
echo "  [OBC]  !!! IMPLANT INSTALLED — Haven-1 compromised"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  AFTER — AEGIS-generated OPA policy applied"
echo "  Policy: haven_update_policy.rego (generated from gap CM0034)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Testing compromised artifact against policy..."
echo ""

conftest test "$ARTIFACT" \
    --policy "$POLICY" \
    --namespace haven.update_policy

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Testing patched artifact (CryptoLib 1.4.2, SBOM verified)..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

conftest test "$HARDENED" \
    --policy "$POLICY" \
    --namespace haven.update_policy

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  RESULT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Without policy: malicious update ships to Haven-1"
echo "  With policy:    update blocked at CI/CD gate"
echo "                  implant never reaches the OBC"
echo "                  crew never at risk"
echo ""
echo "  This policy was auto-generated by AEGIS from gap analysis."
echo "  Deploy time: under 5 minutes."
echo "  Cost to attacker: entire kill chain fails at Step 2."
echo ""
